# Generated by Django 3.0.7 on 2020-06-24 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('dob', models.DateField(default='2020-06-02')),
                ('weight', models.IntegerField(default='50')),
                ('waist', models.IntegerField(default='28')),
                ('hip', models.IntegerField(default='30')),
                ('purpose', models.CharField(choices=[('GW', 'I want to know why I might have gained weight'), ('FR', 'I am more concerned about future risks from this weight gain '), ('BC', 'Want to prepare my body for conception'), ('PR', 'Need to get my prescription renewed'), ('SO', 'Need to get a second opinion'), ('PC', 'Follow up for previous consultation'), ('other', 'Other')], default='GW', max_length=100)),
                ('have_baby', models.CharField(choices=[('y', 'yes'), ('n', 'no')], default='n', max_length=100)),
                ('hyperprolactinemia', models.CharField(blank=True, default='not_there', max_length=100, null=True)),
                ('pcos_pcod', models.CharField(blank=True, default='not_there', max_length=100, null=True)),
                ('hypothyroidism', models.CharField(blank=True, default='not_there', max_length=100, null=True)),
                ('other', models.CharField(blank=True, default='not_there', max_length=100, null=True)),
                ('hyperprolactinemia_days', models.IntegerField(blank=True, default=0, null=True)),
                ('pcos_pcod_days', models.IntegerField(blank=True, default=0, null=True)),
                ('hypothyroidism_days', models.IntegerField(blank=True, default=0, null=True)),
                ('other_days', models.IntegerField(blank=True, default=0, null=True)),
                ('symptoms7', models.CharField(default='none', max_length=100)),
            ],
        ),
    ]
