# Generated by Django 3.0.7 on 2020-06-24 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='month8',
            field=models.CharField(choices=[('JAN', 'JAN'), ('FEB', 'FEB'), ('MAR', 'MAR'), ('APR', 'APR'), ('MAY', 'MAY'), ('JUN', 'JUN'), ('JUL', 'JUL'), ('AUG', 'AUG'), ('SEP', 'SEP'), ('OCT', 'OCT'), ('NOV', 'NOV'), ('DEC', 'DEC')], default='JAN', max_length=100),
        ),
        migrations.AddField(
            model_name='patient',
            name='year8',
            field=models.CharField(choices=[('2019', '2019'), ('2020', '2020')], default='2019', max_length=100),
        ),
    ]
