# Generated by Django 3.0.7 on 2020-06-24 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200624_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='time9',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='time9_d',
            field=models.CharField(choices=[('d', 'days'), ('m', 'months'), ('y', 'years')], default='m', max_length=100),
        ),
        migrations.AddField(
            model_name='patient',
            name='weight9',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
